### ISSUE TITLE
Add ImageGlass 9.0 RC as prerelease

### ISSUE THREAD

**Issue by Vinfall** [Starz0r/ChocolateyPackagingScripts#18]
ImageGlass [8.8.4.4](https://github.com/d2phap/ImageGlass/releases/tag/8.8.4.4) onward does not work for me due to a dependency issue on their side. Usually it's not an issue for me to stay on older version until there is a fix but I noticed that [8.10.9.27](https://github.com/d2phap/ImageGlass/releases/tag/8.10.9.27) fixed a WebP vulnerability [CVE-2023-4863](https://github.com/advisories/GHSA-j7hp-h8jx-5ppr). Since ImageGlass has been baking 9.0 with several beta releases, would you mind adding [9.0 RC](https://github.com/d2phap/ImageGlass/releases/tag/9.0.6.1008) as a prerelease?

**Comment by Starz0r** [comment]
I do this for all my packages where ever possible, but in ImageGlass's case, it isn't possible. At least, not easily. This is because they do not publish MSI binaries for pre-releases, meaning I'd have to use the portable ZIP releases, and I wouldn't want to do that on an “Install-only” package. The alternative would be to run the build process myself to generate the MSIs, but that's a lot of effort, and ImageGlass is a somewhat big piece of software.

The easiest solution would be to contact the ImageGlass maintainers and ask them to publish MSIs on pre-releases (for both x64 and x86). Since my packaging system already enumerates releases, regardless of if they're marked as pre-release or not, they'll be automatically picked up with no extra work required on my side.

**Comment by Vinfall** [comment]
Ah, that's understandable. I'll just use their portable prerelease for the time being then.

**Comment by asheroto** [comment]
Hey guys, looks like last week they just released an official stable version and there's an MSI available.

https://github.com/d2phap/ImageGlass/releases

**Comment by Vinfall** [comment]
I guess it's invalidated in the automation script as ImageGlass dev packages only x64 version in the release:

https://github.com/Starz0r/ChocolateyPackagingScripts/blob/e4586bb24fff128887424bdd4af4a4811086c755/src/imageglass_gh_releases.py#L18-L29

Quoted from [the blog post](https://imageglass.org/news/introducing-the-new-imageglass-version-9-88):

> ImageGlass 9 drops support for Windows 10 version 1909 (November 2019 Update) and older, including Windows 8.1, 8 and 7. Please note that 32-bit x86 version is also no longer supported.

@Starz0r, can you fix this? There is also a (new?) arm64 build by the way in case you wanna package that as well.

**Comment by asheroto** [comment]
Fortunately most users use 64-bit so it likely won't be an issue.

Dropping Windows 10 support might be a slight problem though because the install will just fail I'm guessing. Not sure if the script should include a check for the OS version, or if it should be left as is?

The functions to detect the OS and architecture can be found but here's an easy function I wrote awhile back for similar purposes:
https://gist.github.com/asheroto/cfa26dd00177a03c81635ea774406b2b

**Comment by asheroto** [comment]
Thanks for adding this, but I noticed the "Release Notes" don't look at we would expect them to.

https://community.chocolatey.org/packages/imageglass#releasenotes

![image](https://github.com/Starz0r/ChocolateyPackagingScripts/assets/49938263/4d515999-83b5-49eb-a48e-c3f85b393f51)
