### ISSUE TITLE
Package dust is outdated: 0.8.5 -> 1.0.0

### ISSUE THREAD

**Issue by d-Rickyy-b** [Starz0r/ChocolateyPackagingScripts#19]
Hi there, I was checking out the [dust](https://github.com/bootandy/dust/releases/) package and found that it was still on version 0.8.5. There have been three version bumps since that version. Could you please update the chocolatey package?

Cheers

**Comment by Starz0r** [comment]
Hey, currently there is a problem in submission where packages are currently held up by the overzealous virus scanner. Since I already submitted the last two versions, I can't submit anymore until those two get approved. If you'd like to help out contacting the anti-virus software manufacturers would be immensely helpful.

https://www.virustotal.com/gui/file/4d655425be8d2ead5e4cca92caf206ace084a6619e253143fe346c6eeeeffa8e/detection/f-4d655425be8d2ead5e4cca92caf206ace084a6619e253143fe346c6eeeeffa8e-1707196873
https://www.virustotal.com/gui/file/f77f02c1dc2125bc389eb7e8fb04ea3dc511770eda4b20fad55908d45087d8f5/detection/f-f77f02c1dc2125bc389eb7e8fb04ea3dc511770eda4b20fad55908d45087d8f5-1707196875
https://www.virustotal.com/gui/file/c1c8469b0ac1bf61586b334e373507813c53f43f53b1232b06b5ffafe6eee5a1/detection/f-c1c8469b0ac1bf61586b334e373507813c53f43f53b1232b06b5ffafe6eee5a1-1707196876
https://www.virustotal.com/gui/file/8eafe818ba2e2fe86ef02e9c67ccf7977d71f6614c3ca370429cd89b1bce83fc/detection/f-8eafe818ba2e2fe86ef02e9c67ccf7977d71f6614c3ca370429cd89b1bce83fc-1707196877

In the meanwhile, can I interest you in [erdtree](https://community.chocolatey.org/packages/et)?

**Comment by d-Rickyy-b** [comment]
Hooray, dust was updated to 1.1.0 :)

I tried reporting the file to the AV vendors, I contacted chocolatey and asked for other options. I am glad to see that there's finally a new version of dust on chocolatey.

Cheers
